platform :ios, '9.0'

target 'NavigationBarTransition_Example' do
    use_frameworks!
    inhibit_all_warnings!

    target 'NavigationBarTransition_Tests' do
        inherit! :search_paths
    end

    pod 'NavigationBarTransition', :path => '../NavigationBarTransition.podspec'
end
